# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: SheepD's blog
email: hello@sheepd.com
description: > # this means to ignore newlines until "baseurl:"
  Code so good that you can count sheep at night with peace of mind
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://sheepd.com" # the base hostname & protocol for your site
github_username:  sheepd

# Build settings
markdown: kramdown
